{% set name = "libosxunwind" %}
{% set version = "0.0.4" %}
{% set sha256 = "ba1796f654d2c19e68dd117f2818c15fb4323e736ef8003ff4416c6a7587b9d7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/JuliaLang/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1000
  skip: true  # [not osx]

requirements:
  build:
    - {{ compiler("cxx") }}
  host:

test:
  commands:
    - test -f "${PREFIX}/include/libunwind.h"
    - test -f "${PREFIX}/include/unwind.h"
    - test -d "${PREFIX}/include/mach-o"
    - test -f "${PREFIX}/lib/libosxunwind.a"
    - test -f "${PREFIX}/lib/libosxunwind.dylib"

    - conda inspect linkages -p "${PREFIX}" "{{ name }}"
    - conda inspect objects -p "${PREFIX}" "{{ name }}"

about:
  home: https://github.com/JuliaLang/libosxunwind
  license: APSL-2.0
  # No license file included. Raise an issue upstream.
  #
  # xref: https://github.com/JuliaLang/libosxunwind/issues/10
  license_file: "{{ RECIPE_DIR }}/LICENSE.txt"
  license_url: https://opensource.apple.com/apsl
  summary: Clone of Apple's libunwind, enhanced for the Julia Profiler
  dev_url: https://github.com/JuliaLang/libosxunwind

extra:
  recipe-maintainers:
    - dfornika
    - jakirkham
