appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: QTTsk14WF9TYDTjzGOiDGYxSSUdOJvL66KjH20z6QjGq1eMSsGeTwndOoIaZZgyLHHIqTjs4bs6L9axAssPJQybqxRaEA4iotSdDQ6F9PCoMiqkTCA7TgU1u877+vFD0Ot7nFEeqeqpKRACLpC52cheFhDfEbVxmUa8+c8dAFjYm5zhHhPRs27Q1CL9z76im56ut9NZdu9qNsDV4YgMMnUGbSHVNfyX79C3TAv3DkAWbWp02A5pNf/HqA1flSC0cWUjTZV0b6jhn9iEkMB1c7pkisCBpYwa293IA7FL7nPuBpTKy9gnRwKihUqgTSxCVUEq1vjFhXZTg8Mlq/aOtudj6wghc5zfO08Q+F+vzkw7HzCNJuVLXS5OsuBKMPmOzrCvUbTUy8cyCim3JCT+gMHlKKXBA3IbkwOnnTR9EPx3XmytCQZAcFs9bzUCrOJSs8TszNICMUM5pkIbIcmGMZX9szB2s1cKGMWCvMkeL/sS4sYKdIY6+LTHkXR72wh7f5wkigyU3vqKDe/3Dab8qk46D/ClB+mvYD9+mIAGaHouzq3/7rZ3nGOscc+ChF28sbPoXlJjfnVYBYYFSzEzVZ5fazKrcuTkcPDzyql8OYbPJqkFU/hBYTQCg5f9jy8CbtsY7voYaw9JWEhVh1WvJ+pyHOndwn1rTqi3Kbmr983A=}
